#!/usr/bin/env python3
"""One-off generator: Panorama glove catalog -> C++ lookup table for mvm_debug labels."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INC = ROOT / "AfxHookSource2/Filmmaker/Panorama/CameraEditorCosmeticsCatalog.inc"
OUT = ROOT / "AfxHookSource2/Filmmaker/Cosmetics/CosmeticGloveSkinTable.cpp"

text = INC.read_text(encoding="utf-8")
pat = re.compile(r'\["([^"]+)","(\d+):(\d+)"')
entries = []
in_gloves = False
for line in text.splitlines():
    if "gloves:" in line:
        in_gloves = True
    if in_gloves and line.strip().startswith("agents:"):
        break
    m = pat.search(line)
    if m and in_gloves:
        entries.append((int(m.group(2)), int(m.group(3)), m.group(1)))

entries.sort(key=lambda e: (e[0], e[1]))

lines = [
    "// Auto-generated by misc/gen_glove_skin_table.py from CameraEditorCosmeticsCatalog.inc",
    "// Do not edit by hand; re-run the script when the UI glove catalog changes.",
    '#include "CosmeticGloveLabels.h"',
    "",
    "namespace Filmmaker {",
    "namespace CosmeticGloveLabels {",
    "",
    "struct SkinRow { int defIndex; int paintKit; const char* label; };",
    "",
    "static const SkinRow kGloveSkinRows[] = {",
]
for d, p, label in entries:
    esc = label.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'\t{{ {d}, {p}, "{esc}" }},')
lines += [
    "};",
    "",
    "const char* LookupSkinLabel(int defIndex, int paintKit) {",
    "\tfor (const SkinRow& r : kGloveSkinRows) {",
    "\t\tif (r.defIndex == defIndex && r.paintKit == paintKit)",
    "\t\t\treturn r.label;",
    "\t}",
    "\treturn nullptr;",
    "}",
    "",
    "} // namespace CosmeticGloveLabels",
    "} // namespace Filmmaker",
    "",
]

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(entries)} rows -> {OUT}")
