#include "stdafx.h"

#include "ViewportScaler.h"

#include "AfxShaders.h"
#include "WrpConsole.h" // advancedfx::Message (temporary diagnostics)

#include "../shaders/build/afx_drawtexture_vs_5_0.h" // autogenerated (reused VS)
#include "../shaders/build/afx_blit_ps_5_0.h"        // autogenerated (no-clip blit PS)

#define _XM_NO_INTRINSICS_
#include <DirectXMath.h>

namespace {

// Same 52-byte vertex layout afx_drawtexture_vs_5_0 expects (POSITION + COLOR + 3x TEXCOORD).
// The scaler only fills POSITION (screen-space NDC) and TEXCOORD0.xy (UV); the rest is padding
// the VS ignores.
struct Vertex {
	float x, y, z;
	DWORD diffuse;
	float t0u, t0v, t0w;
	float t1u, t1v, t1w;
	float t2u, t2v, t2w;
};

// Matches the VS_CONSTANT_BUFFER cbuffer in afx_drawtexture_vs_5_0.fxc (float4x4 + 3 padded
// float vectors). Only the matrix is used; the scaler sets it to identity so vertex positions
// pass straight through as NDC (o = mul(float4(pos,1), I) / w).
struct VS_CONSTANT_BUFFER {
	DirectX::XMFLOAT4X4 matrix;
	DirectX::XMFLOAT4 plane0;
	DirectX::XMFLOAT4 planeN;
	DirectX::XMFLOAT4 screenInfo;
};

// Fallback only: map a TYPELESS backbuffer format to a sensible typed format for the SRV, used
// if the render-target view somehow reports DXGI_FORMAT_UNKNOWN. Normally the RTV's own (typed)
// format is used instead. Non-typeless inputs pass through unchanged.
DXGI_FORMAT TypedFromTypeless(DXGI_FORMAT f) {
	switch (f) {
	case DXGI_FORMAT_R8G8B8A8_TYPELESS:    return DXGI_FORMAT_R8G8B8A8_UNORM;
	case DXGI_FORMAT_B8G8R8A8_TYPELESS:    return DXGI_FORMAT_B8G8R8A8_UNORM;
	case DXGI_FORMAT_B8G8R8X8_TYPELESS:    return DXGI_FORMAT_B8G8R8X8_UNORM;
	case DXGI_FORMAT_R10G10B10A2_TYPELESS: return DXGI_FORMAT_R10G10B10A2_UNORM;
	case DXGI_FORMAT_R16G16B16A16_TYPELESS:return DXGI_FORMAT_R16G16B16A16_FLOAT;
	default:                               return f;
	}
}

// Full-NDC quad (triangle strip), top row first so UV.v=0 maps to screen top. Cull is disabled
// so winding is irrelevant.
const Vertex c_Quad[4] = {
	{ -1.0f,  1.0f, 0.0f, 0xffffffff, 0.0f, 0.0f, 0.0f, 0,0,0, 0,0,0 }, // top-left     uv(0,0)
	{  1.0f,  1.0f, 0.0f, 0xffffffff, 1.0f, 0.0f, 0.0f, 0,0,0, 0,0,0 }, // top-right    uv(1,0)
	{ -1.0f, -1.0f, 0.0f, 0xffffffff, 0.0f, 1.0f, 0.0f, 0,0,0, 0,0,0 }, // bottom-left  uv(0,1)
	{  1.0f, -1.0f, 0.0f, 0xffffffff, 1.0f, 1.0f, 0.0f, 0,0,0, 0,0,0 }, // bottom-right uv(1,1)
};

} // namespace

CViewportScaler::~CViewportScaler() {
	EndDevice();
}

bool CViewportScaler::Ready() const {
	return m_Device && m_DeviceContext && m_VertexShader && m_PixelShader && m_InputLayout
		&& m_VertexBuffer && m_ConstantBuffer && m_SamplerState && m_RasterizerState
		&& m_DepthStencilState && m_BlendState;
}

void CViewportScaler::BeginDevice(ID3D11Device* device) {
	EndDevice();

	if (nullptr == device)
		return;

	device->AddRef();
	m_Device = device;
	m_Device->CreateDeferredContext(0, &m_DeviceContext);

	// Vertex shader + input layout (reuse the proven afx_drawtexture VS).
	{
		size_t size;
		void* so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_vs_5_0.acs", ShaderCombo_afx_drawtexture_vs_5_0::GetCombo(), size);
		if (so) {
			m_Device->CreateVertexShader(so, size, NULL, &m_VertexShader);

			D3D11_INPUT_ELEMENT_DESC inputDesc[5] = {
				{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,  0, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"COLOR",    0, DXGI_FORMAT_B8G8R8A8_UNORM,  0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 1, DXGI_FORMAT_R32G32B32_FLOAT, 0, 28, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 2, DXGI_FORMAT_R32G32B32_FLOAT, 0, 40, D3D11_INPUT_PER_VERTEX_DATA, 0},
			};
			m_Device->CreateInputLayout(inputDesc, 5, so, size, &m_InputLayout);
		}
		if (so) free(so);
	}

	// Pixel shader (no-clip opaque blit).
	{
		size_t size;
		void* so = LoadFromAcsShaderFileInMemory(L"afx_blit_ps_5_0.acs", ShaderCombo_afx_blit_ps_5_0::GetCombo(), size);
		if (so) {
			m_Device->CreatePixelShader(so, size, NULL, &m_PixelShader);
		}
		if (so) free(so);
	}

	// Static NDC quad vertex buffer.
	{
		D3D11_BUFFER_DESC bd = {};
		bd.ByteWidth = sizeof(c_Quad);
		bd.Usage = D3D11_USAGE_IMMUTABLE;
		bd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
		D3D11_SUBRESOURCE_DATA srd = {};
		srd.pSysMem = c_Quad;
		m_Device->CreateBuffer(&bd, &srd, &m_VertexBuffer);
	}

	// Static identity constant buffer (NDC pass-through).
	{
		VS_CONSTANT_BUFFER cb = {};
		cb.matrix = DirectX::XMFLOAT4X4(
			1, 0, 0, 0,
			0, 1, 0, 0,
			0, 0, 1, 0,
			0, 0, 0, 1); // identity -> vertex positions pass through as NDC

		D3D11_BUFFER_DESC bd = {};
		bd.ByteWidth = sizeof(cb);
		bd.Usage = D3D11_USAGE_IMMUTABLE;
		bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		D3D11_SUBRESOURCE_DATA srd = {};
		srd.pSysMem = &cb;
		m_Device->CreateBuffer(&bd, &srd, &m_ConstantBuffer);
	}

	// Linear clamp sampler.
	{
		D3D11_SAMPLER_DESC sd = {};
		sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		sd.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.ComparisonFunc = D3D11_COMPARISON_ALWAYS;
		sd.MinLOD = 0;
		sd.MaxLOD = D3D11_FLOAT32_MAX;
		m_Device->CreateSamplerState(&sd, &m_SamplerState);
	}

	// Solid fill, no culling (the quad winding is irrelevant).
	{
		D3D11_RASTERIZER_DESC rd = {};
		rd.FillMode = D3D11_FILL_SOLID;
		rd.CullMode = D3D11_CULL_NONE;
		rd.DepthClipEnable = TRUE;
		m_Device->CreateRasterizerState(&rd, &m_RasterizerState);
	}

	// Depth test/write disabled (no depth buffer is bound for the blit).
	{
		D3D11_DEPTH_STENCIL_DESC dd = {};
		dd.DepthEnable = FALSE;
		dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		dd.DepthFunc = D3D11_COMPARISON_ALWAYS;
		dd.StencilEnable = FALSE;
		m_Device->CreateDepthStencilState(&dd, &m_DepthStencilState);
	}

	// Opaque overwrite (the rect is fully covered, so no blending).
	{
		D3D11_BLEND_DESC bd = {};
		bd.RenderTarget[0].BlendEnable = FALSE;
		bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
		m_Device->CreateBlendState(&bd, &m_BlendState);
	}
}

void CViewportScaler::ReleaseTemp() {
	if (m_TempSrv) { m_TempSrv->Release(); m_TempSrv = nullptr; }
	if (m_TempTexture) { m_TempTexture->Release(); m_TempTexture = nullptr; }
	m_TempWidth = 0;
	m_TempHeight = 0;
	m_TempFormat = DXGI_FORMAT_UNKNOWN;
}

void CViewportScaler::EndDevice() {
	ReleaseTemp();

	if (m_BlendState) { m_BlendState->Release(); m_BlendState = nullptr; }
	if (m_DepthStencilState) { m_DepthStencilState->Release(); m_DepthStencilState = nullptr; }
	if (m_RasterizerState) { m_RasterizerState->Release(); m_RasterizerState = nullptr; }
	if (m_SamplerState) { m_SamplerState->Release(); m_SamplerState = nullptr; }
	if (m_ConstantBuffer) { m_ConstantBuffer->Release(); m_ConstantBuffer = nullptr; }
	if (m_VertexBuffer) { m_VertexBuffer->Release(); m_VertexBuffer = nullptr; }
	if (m_InputLayout) { m_InputLayout->Release(); m_InputLayout = nullptr; }
	if (m_PixelShader) { m_PixelShader->Release(); m_PixelShader = nullptr; }
	if (m_VertexShader) { m_VertexShader->Release(); m_VertexShader = nullptr; }
	if (m_DeviceContext) { m_DeviceContext->Release(); m_DeviceContext = nullptr; }
	if (m_Device) { m_Device->Release(); m_Device = nullptr; }
}

bool CViewportScaler::EnsureTemp(const D3D11_TEXTURE2D_DESC& bb, DXGI_FORMAT viewFormat) {
	if (m_TempTexture && m_TempSrv
		&& m_TempWidth == bb.Width && m_TempHeight == bb.Height && m_TempFormat == viewFormat)
		return true;

	ReleaseTemp();

	// Use the TYPED view format (not bb.Format, which may be TYPELESS). A typed temp texture is
	// still CopyResource/ResolveSubresource-compatible with the backbuffer (same format group).
	D3D11_TEXTURE2D_DESC td = {};
	td.Width = bb.Width;
	td.Height = bb.Height;
	td.MipLevels = 1;
	td.ArraySize = 1;
	td.Format = viewFormat;
	td.SampleDesc.Count = 1;          // single-sample so we can sample it as an SRV
	td.SampleDesc.Quality = 0;
	td.Usage = D3D11_USAGE_DEFAULT;
	td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	if (FAILED(m_Device->CreateTexture2D(&td, nullptr, &m_TempTexture)) || !m_TempTexture) {
		ReleaseTemp();
		return false;
	}

	D3D11_SHADER_RESOURCE_VIEW_DESC sd = {};
	sd.Format = viewFormat;
	sd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	sd.Texture2D.MostDetailedMip = 0;
	sd.Texture2D.MipLevels = 1;
	if (FAILED(m_Device->CreateShaderResourceView(m_TempTexture, &sd, &m_TempSrv)) || !m_TempSrv) {
		ReleaseTemp();
		return false;
	}

	m_TempWidth = bb.Width;
	m_TempHeight = bb.Height;
	m_TempFormat = viewFormat;
	return true;
}

void CViewportScaler::Blit(ID3D11DeviceContext* pImmediateContext, ID3D11RenderTargetView* pTarget,
	float x0, float y0, float x1, float y1) {
	// Diagnostics: only emit when the OUTCOME changes (no per-frame spam). s_prevCode tracks
	// the last outcome; bb size is tracked too so a resolution change re-logs the RUN line.
	static int s_prevCode = -999;
	static UINT s_prevW = 0, s_prevH = 0;
	auto changed = [&](int code) { if (s_prevCode != code) { s_prevCode = code; return true; } return false; };

	if (!Ready() || !pImmediateContext || !pTarget) {
		if (changed(1)) advancedfx::Message("[vpscale] blit SKIP: ready=%d ctx=%p tgt=%p\n",
			(int)Ready(), (void*)pImmediateContext, (void*)pTarget);
		return;
	}

	ID3D11Resource* pResource = nullptr;
	pTarget->GetResource(&pResource);
	if (!pResource)
		return;

	ID3D11Texture2D* pBackbuffer = nullptr;
	if (FAILED(pResource->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&pBackbuffer)) || !pBackbuffer) {
		if (changed(2)) advancedfx::Message("[vpscale] blit SKIP: RTV resource is not a Texture2D\n");
		pResource->Release();
		return;
	}

	D3D11_TEXTURE2D_DESC bbDesc;
	pBackbuffer->GetDesc(&bbDesc);

	// The backbuffer can be TYPELESS, which can't back an SRV. Use the render-target view's
	// typed format for the temp texture / SRV / resolve instead (fall back to a typed mapping).
	D3D11_RENDER_TARGET_VIEW_DESC rtvDesc;
	pTarget->GetDesc(&rtvDesc);
	DXGI_FORMAT viewFmt = rtvDesc.Format;
	if (viewFmt == DXGI_FORMAT_UNKNOWN) viewFmt = TypedFromTypeless(bbDesc.Format);

	if (!EnsureTemp(bbDesc, viewFmt)) {
		if (changed(3)) advancedfx::Message("[vpscale] blit SKIP: EnsureTemp failed (%ux%u bbfmt=%d viewfmt=%d)\n",
			bbDesc.Width, bbDesc.Height, (int)bbDesc.Format, (int)viewFmt);
		pBackbuffer->Release();
		pResource->Release();
		return;
	}

	const float fw = (float)bbDesc.Width;
	const float fh = (float)bbDesc.Height;

	// Clamp the fractions and bail on a degenerate rect.
	auto clamp01 = [](float v) { return v < 0.0f ? 0.0f : (v > 1.0f ? 1.0f : v); };
	x0 = clamp01(x0); y0 = clamp01(y0); x1 = clamp01(x1); y1 = clamp01(y1);
	if (x1 - x0 < 0.001f || y1 - y0 < 0.001f) {
		if (changed(4)) advancedfx::Message("[vpscale] blit SKIP: degenerate rect %.3f %.3f %.3f %.3f\n",
			x0, y0, x1, y1);
		pBackbuffer->Release();
		pResource->Release();
		return;
	}

	// 1. Snapshot the rendered frame into the temp texture (resolve if the backbuffer is MSAA).
	if (bbDesc.SampleDesc.Count > 1)
		m_DeviceContext->ResolveSubresource(m_TempTexture, 0, pBackbuffer, 0, viewFmt);
	else
		m_DeviceContext->CopyResource(m_TempTexture, pBackbuffer);

	// 2. Clear the backbuffer black.
	const float black[4] = { 0.0f, 0.0f, 0.0f, 1.0f };
	m_DeviceContext->ClearRenderTargetView(pTarget, black);

	// 3. Draw the whole snapshot scaled into the preview rect.
	ID3D11RenderTargetView* rtvs[1] = { pTarget };
	m_DeviceContext->OMSetRenderTargets(1, rtvs, nullptr);

	D3D11_VIEWPORT vp = {};
	vp.TopLeftX = x0 * fw;
	vp.TopLeftY = y0 * fh;
	vp.Width = (x1 - x0) * fw;
	vp.Height = (y1 - y0) * fh;
	vp.MinDepth = 0.0f;
	vp.MaxDepth = 1.0f;
	m_DeviceContext->RSSetViewports(1, &vp);

	// Record the actual numbers for the camera-editor debug overlay (read on the main thread).
	m_LastBbWidth = bbDesc.Width; m_LastBbHeight = bbDesc.Height;
	m_LastVp[0] = vp.TopLeftX; m_LastVp[1] = vp.TopLeftY; m_LastVp[2] = vp.Width; m_LastVp[3] = vp.Height;
	m_LastBlitRan = true;

	if (s_prevCode != 5 || s_prevW != bbDesc.Width || s_prevH != bbDesc.Height) {
		s_prevCode = 5; s_prevW = bbDesc.Width; s_prevH = bbDesc.Height;
		advancedfx::Message("[vpscale] blit RUN: bb=%ux%u fmt=%d samples=%u -> vp x=%.0f y=%.0f w=%.0f h=%.0f\n",
			bbDesc.Width, bbDesc.Height, (int)bbDesc.Format, bbDesc.SampleDesc.Count,
			vp.TopLeftX, vp.TopLeftY, vp.Width, vp.Height);
	}

	m_DeviceContext->IASetInputLayout(m_InputLayout);
	UINT stride = sizeof(Vertex);
	UINT offset = 0;
	m_DeviceContext->IASetVertexBuffers(0, 1, &m_VertexBuffer, &stride, &offset);
	m_DeviceContext->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);

	m_DeviceContext->VSSetShader(m_VertexShader, nullptr, 0);
	m_DeviceContext->VSSetConstantBuffers(0, 1, &m_ConstantBuffer);
	m_DeviceContext->PSSetShader(m_PixelShader, nullptr, 0);
	m_DeviceContext->PSSetShaderResources(0, 1, &m_TempSrv);
	m_DeviceContext->PSSetSamplers(0, 1, &m_SamplerState);

	m_DeviceContext->RSSetState(m_RasterizerState);
	m_DeviceContext->OMSetDepthStencilState(m_DepthStencilState, 0);
	const float blendFactor[4] = { 0, 0, 0, 0 };
	m_DeviceContext->OMSetBlendState(m_BlendState, blendFactor, 0xffffffff);

	m_DeviceContext->Draw(4, 0);

	// Replay on the immediate context, restoring its state so the following UI pass is intact.
	ID3D11CommandList* pCommandList = nullptr;
	m_DeviceContext->FinishCommandList(FALSE, &pCommandList);
	if (pCommandList) {
		pImmediateContext->ExecuteCommandList(pCommandList, TRUE);
		pCommandList->Release();
	}

	pBackbuffer->Release();
	pResource->Release();
}
